/**
 * Web Push Notification Client Service for ApplyFlow.
 * Handles Service Worker registration, VAPID key exchange, subscription lifecycle,
 * and background notification permissions.
 */

import api from '@/services/api';

/**
 * Converts a URL-safe Base64 string to a Uint8Array for PushManager applicationServerKey.
 */
function urlBase64ToUint8Array(base64String) {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

/**
 * Check if the current browser environment supports Service Workers and Web Push.
 */
export function isPushNotificationSupported() {
  return (
    typeof window !== 'undefined' &&
    'serviceWorker' in navigator &&
    'PushManager' in window &&
    'Notification' in window
  );
}

/**
 * Get current browser notification permission status ('default', 'granted', 'denied').
 */
export function getNotificationPermission() {
  if (!isPushNotificationSupported()) return 'denied';
  return Notification.permission;
}

/**
 * Register the ApplyFlow Service Worker (/sw.js).
 */
export async function registerServiceWorker() {
  if (!isPushNotificationSupported()) return null;

  try {
    const registration = await navigator.serviceWorker.register('/sw.js', {
      scope: '/',
    });
    // Check for Service Worker updates immediately
    if (registration && typeof registration.update === 'function') {
      registration.update().catch(() => {});
    }
    return registration;
  } catch (err) {
    console.warn('[PushNotifications] Service worker registration failed:', err);
    return null;
  }
}

/**
 * Prompt user for notification permission and register push subscription with backend.
 */
export async function subscribeToPushNotifications() {
  if (!isPushNotificationSupported()) {
    throw new Error('Web Push Notifications are not supported in this browser.');
  }

  // 1. Request Notification permission
  const permission = await Notification.requestPermission();
  if (permission !== 'granted') {
    return { success: false, permission, reason: 'Permission not granted' };
  }

  // 2. Ensure Service Worker is active
  let registration = await navigator.serviceWorker.ready;
  if (!registration) {
    registration = await registerServiceWorker();
    registration = await navigator.serviceWorker.ready;
  }

  // 3. Retrieve VAPID Public Key from backend
  const vapidRes = await api.get('/chat/push/vapid-public-key');
  const publicKey = vapidRes.data?.public_key;
  if (!publicKey) {
    throw new Error('Server VAPID public key is missing or not configured.');
  }

  // 4. Subscribe or renew with browser PushManager
  let subscription = await registration.pushManager.getSubscription();
  if (!subscription) {
    const applicationServerKey = urlBase64ToUint8Array(publicKey);
    subscription = await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey,
    });
  }

  // 5. Serialize subscription keys
  const subJson = subscription.toJSON();
  const endpoint = subJson.endpoint;
  const p256dh = subJson.keys?.p256dh;
  const auth = subJson.keys?.auth;

  if (!endpoint || !p256dh || !auth) {
    throw new Error('Incomplete push subscription generated by browser.');
  }

  // 6. Send subscription to ApplyFlow backend
  await api.post('/chat/push/subscribe', {
    endpoint,
    keys: {
      p256dh,
      auth,
    },
  });

  return { success: true, permission, subscription };
}

/**
 * Unsubscribe this browser device from Push Notifications.
 */
export async function unsubscribeFromPushNotifications() {
  if (!isPushNotificationSupported()) return { success: false };

  try {
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.getSubscription();

    if (subscription) {
      const endpoint = subscription.endpoint;
      await subscription.unsubscribe();
      await api.delete('/chat/push/unsubscribe', {
        data: { endpoint },
      });
    }

    return { success: true };
  } catch (err) {
    console.error('[PushNotifications] Failed to unsubscribe:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Initializes push notifications silently if permission has already been granted.
 * Call this on app load / after login.
 */
export async function initPushNotifications() {
  if (!isPushNotificationSupported()) return;

  try {
    await registerServiceWorker();

    if (Notification.permission === 'granted') {
      await subscribeToPushNotifications();
    }
  } catch (err) {
    console.debug('[PushNotifications] Silent push init:', err.message);
  }
}
