"""initial_neon_schema

Revision ID: 84e0aa572138
Revises: 
Create Date: 2026-08-26 20:12:31.408870
"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '84e0aa572138'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
